[package]
name = "pf-elevated"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies.windows]
version = "0.62"
features = [
    "Win32_System_Diagnostics_Etw",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Time",
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
]

[[bin]]
name = "pf-elevated"
path = "src/main.rs"
